#!/usr/bin/env bash

#############################################################################
# @ddblock_begin copyright 
#
# Copyright (c) 1999-2011
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright 
#############################################################################

# Startup file for DICE. This is a standard startup file. It should 
# typically be used "as is," without modifications.
# 
# This file should be sourced from the dice_user directory. It should
# be run using "source startup/dice_startup [raw]".
#
# The optional "raw" argument disables linkage of user-defined
# bash customiations (taken from dice_user/startup/customizations).
# The raw version is useful for
# making sure results can be reproduced independently of one's customizations.
#
# Usage: source startup/dice_startup [raw]
# Version: 07/04/2011

# Export definitions to subprocesses 
set -a

# A simple function that displays the message given by the script arguments
# (all arguments make up the message)
# if the value of the DXVERBOSE environment variable is a non-empty string.
function dx_diagnostic { 
    if [ -n "$DXVERBOSE" ]; then
        echo $@
    fi
}

# Load UX customizations that are needed upon startup.
if ! [ -f startup/uxdefs_dice ]; then
    echo dice startup error: cannot find uxdefs_dice file
    exit 1
fi
nextscript=`pwd`/startup/uxdefs_dice
dx_diagnostic starting $nextscript 
source $nextscript
dx_diagnostic finished with $nextscript

# The location of dice user directory.
DXUSER=`pwd`

# Load the standard DICE configuration.
nextscript=$UXDICE/config/startup/standard_startup
dx_diagnostic starting $nextscript 
source $nextscript
dx_diagnostic finished with $nextscript

# Link in user-defined customizations unless the "raw"
# option is selected.
if [ "$1" != raw ]; then
    if [ -f $DXUSER/startup/customizations ]; then
        nextscript=$DXUSER/startup/customizations
        dx_diagnostic starting $nextscript
        source $nextscript
        dx_diagnostic finished with $nextscript
    fi
fi

