#!/bin/bash

gcc -c main.c -Wall -pedantic
gcc -c bubbleSort.c -Wall -pedantic
gcc -c meanArray.c -Wall -pedantic
gcc -c medianArray.c -Wall -pedantic
gcc -o main.exe main.o bubbleSort.o meanArray.o medianArray.o
