#!/usr/bin/env bash

#############################################################################
# Copyright (c) 1999-2011
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#############################################################################

# Startup file for dicelang. This is a standard startup file. It should 
# typically be used "as is," without modifications.
# 
# This file should be dxsourced from the dice_user/dice_lang directory. 
# It should be run using "dxsource startup/dicelang_startup".
#
# Usage: dxsource startup/dicelang_startup 
# Version: 07/04/2011

# Export definitions to subprocesses 
set -a

# Load UX customizations that are needed upon startup.
if ! [ -f startup/uxdefs_dicelang ]; then
    echo dicelang startup error: cannot find uxdefs_dicelang file
    exit 1
fi
dxsource startup/uxdefs_dicelang

# The location of the dicelang user directory.
DLXUSER=`pwd`

# Load the standard dicelang configuration.
dxsource $UXDICELANG/config/startup/standard_startup

